version: 2
updates:
  # --- DEPENDENCIAS DE PYTHON ---
  - package-ecosystem: "pip"
    directory: "/"             # requirements.txt está en raíz
    schedule:
      interval: "weekly"      
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all" # actualiza prod + dev

  # --- IMÁGENES DOCKER ---
  - package-ecosystem: "docker"
    directory: "/"             # Dockerfile está en raíz
    schedule:
      interval: "weekly"

  # --- GITHUB ACTIONS ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
